=== Aspard/PAndroide/data/plans/bp.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Element racine -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <!-- declaration des elements -->
    <xsd:element name="coordonnees" type="xsd:string"/>
    <xsd:element name="coordEtNomPieceConnexe" type="xsd:string"/>
    <xsd:element name="batiment" type="batimentType"/>
    <xsd:element name="murs" type="mursType"/>
    <xsd:element name="obstacles" type="obstaclesType"/>
    <xsd:element name="obstacle" type="obstacleType"/>
    <xsd:element name="piece" type="pieceType"/>
    <xsd:element name="sortie" type="sortieType"/>

    <!-- murs -->
    <xsd:complexType name="mursType">
        <xsd:sequence>
            <xsd:element ref="coordonnees" maxOccurs ="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>


    <!-- obstacle -->
    <xsd:complexType name="obstacleType">
        <xsd:sequence>
            <xsd:element ref="coordonnees" maxOccurs ="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <!-- obstacles -->
    <xsd:complexType name="obstaclesType">
        <xsd:sequence>
            <xsd:element name="nom" type="xsd:string"/>
            <xsd:element ref="obstacle" maxOccurs ="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <!-- sorties -->
    <xsd:complexType name="sortieType">
        <xsd:sequence>
            <xsd:element ref="coordEtNomPieceConnexe" maxOccurs ="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <!-- piece -->
    <xsd:complexType name="pieceType">
        <!-- nom de la piece -->
        <xsd:all>
            <xsd:element name="nom" type="xsd:string"/>
            <xsd:element ref="murs"/>
            <xsd:element ref="obstacles" minOccurs="0"/>
            <xsd:element ref="sortie"/>
        </xsd:all>
    </xsd:complexType>

    <!-- Batiment -->
    <xsd:complexType name="batimentType">
            <!-- nom du batiment -->
            <!-- Liste des pieces -->
            <xsd:sequence id="test">
                <xsd:element name="nom" type="xsd:string"/>
                <xsd:element ref="piece" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
    </xsd:complexType>

    <!-- Racine -->
    <xsd:element name="racine">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="batiment"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== Aspard/PAndroide/data/plans/blueprint.xml
<?xml version="1.0" encoding="UTF-8"?>

<racine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="./bp.xsd" >
  
  <batiment>
    <nom>Test</nom>
    
    <piece>
        <nom>piece7</nom>
        <murs>
            <coordonnees>2;4,0;4</coordonnees>  
            <coordonnees>0;4,0;0</coordonnees>
            <coordonnees>0;0,6;0</coordonnees>
            <coordonnees>6;0,6;4</coordonnees>
            <coordonnees>6;4,4;4</coordonnees>             
        </murs>
        <sortie>
            <coordEtNomPieceConnexe>3;4,piece5</coordEtNomPieceConnexe>
        </sortie>
    </piece>
    
    <piece>
        <nom>piece1</nom>
        <murs>
            <coordonnees>4;5,0;5</coordonnees>  
            <coordonnees>0;5,0;0</coordonnees>
            <coordonnees>0;0,7;0</coordonnees>
            <coordonnees>7;0,7;5</coordonnees>
            <coordonnees>7;5,6;5</coordonnees>             
        </murs>
        <obstacles>
            <obstacle>
                <nom>tablereunion</nom>
                <coordonnees>2;2,5;2</coordonnees>  
                <coordonnees>5;2,5;3</coordonnees>
                <coordonnees>5;3,2;3</coordonnees>
                <coordonnees>2;3,2;2</coordonnees>
            </obstacle>      
        </obstacles>
        <sortie>
            <coordEtNomPieceConnexe>5;5,piece2</coordEtNomPieceConnexe>
        </sortie>
    </piece>
    
    <piece>
        <nom>piece2</nom>
        <murs>
            <coordonnees>3;0,0;0</coordonnees>  
            <coordonnees>0;0,0;7</coordonnees>
            <coordonnees>0;7,3;7</coordonnees>
            <coordonnees>3;7,3;5</coordonnees>
            <coordonnees>3;5,4;5</coordonnees>
            <coordonnees>6;5,6;3</coordonnees>
            <coordonnees>6;1,6;0</coordonnees>      
            <coordonnees>6;0,5;0</coordonnees>        
        </murs>
        <obstacles>
            <obstacle>
                <nom>bar</nom>
                <coordonnees>0;3,1;3</coordonnees>  
                <coordonnees>1;3,1;7</coordonnees>
                <coordonnees>1;7,0;7</coordonnees>
                <coordonnees>0;7,0;3</coordonnees>
            </obstacle>      
        </obstacles>
        <sortie>
            <coordEtNomPieceConnexe>4;0,piece1</coordEtNomPieceConnexe>
            <coordEtNomPieceConnexe>5;5,piece3</coordEtNomPieceConnexe>
            <coordEtNomPieceConnexe>6;2,piece4</coordEtNomPieceConnexe>
        </sortie>
    </piece>

    <piece>
        <nom>piece4</nom>
        <murs>
            <coordonnees>0;1,0;0</coordonnees>
            <coordonnees>0;0,1;0</coordonnees>
            <coordonnees>3;0,4;0</coordonnees>
            <coordonnees>4;0,4;9</coordonnees>
            <coordonnees>4;9,1;9</coordonnees>
            <coordonnees>1;9,1;5</coordonnees>
            <coordonnees>1;5,0;5</coordonnees>
            <coordonnees>0;5,0;3</coordonnees>
        </murs>
        <obstacles>
            <obstacle>
                <nom>comptoir</nom>
                <coordonnees>4;2,2;2</coordonnees>
                <coordonnees>2;2,2;3</coordonnees>
                <coordonnees>2;3,3;3</coordonnees>
                <coordonnees>3;3,3;7</coordonnees>
                <coordonnees>3;7,4;7</coordonnees>
                <coordonnees>4;7,4;2</coordonnees>
            </obstacle>
        </obstacles>
        <sortie>
            <coordEtNomPieceConnexe>0;2,piece2</coordEtNomPieceConnexe>
            <coordEtNomPieceConnexe>2;0,piece5</coordEtNomPieceConnexe>
        </sortie>
    </piece>

    <piece>
        <nom>piece3</nom>
        <murs>
            <coordonnees>1;0,0;0</coordonnees>   
            <coordonnees>0;0,0;4</coordonnees> 
            <coordonnees>0;4,3;4</coordonnees>
            <coordonnees>3;4,3;0</coordonnees>
        </murs>
        <sortie>
            <coordEtNomPieceConnexe>2;0,piece2</coordEtNomPieceConnexe>
        </sortie>
    </piece>
    
    <piece>
        <nom>piece5</nom>
        <murs>
            <coordonnees>0;0,4;0</coordonnees>
            <coordonnees>4;0,4;1</coordonnees>
            <coordonnees>4;3,4;4</coordonnees>
            <coordonnees>4;4,11;4</coordonnees>
            <coordonnees>11;4,11;6</coordonnees>
            <coordonnees>11;6,8;6</coordonnees>
            <coordonnees>6;6,4;6</coordonnees>
            <coordonnees>4;6,4;8</coordonnees>
            <coordonnees>4;10,4;15</coordonnees>
            <coordonnees>4;15,3;15</coordonnees>
            <coordonnees>1;15,0;15</coordonnees>
            <coordonnees>0;15,0;6</coordonnees>
            <coordonnees>0;6,-2;6</coordonnees>
            <coordonnees>-4;6,-6;6</coordonnees>
            <coordonnees>-6;6,-6;4</coordonnees>
            <coordonnees>-6;4,-4;4</coordonnees>
            <coordonnees>-2;4,0;4</coordonnees>
            <coordonnees>0;4,0;0</coordonnees>        
        </murs>
        <sortie>
            <coordEtNomPieceConnexe>2;15,piece4</coordEtNomPieceConnexe>
            <coordEtNomPieceConnexe>-3;6,piece6</coordEtNomPieceConnexe>
            <coordEtNomPieceConnexe>-3;4,piece7</coordEtNomPieceConnexe>
            <coordEtNomPieceConnexe>4;2,piece8</coordEtNomPieceConnexe>
            <coordEtNomPieceConnexe>4;9,piece9</coordEtNomPieceConnexe>
            <coordEtNomPieceConnexe>7;6,piece9</coordEtNomPieceConnexe>
        </sortie>
    </piece>
    
    <piece>
        <nom>piece6</nom>
        <murs>
            <coordonnees>2;0,0;0</coordonnees>  
            <coordonnees>0;0,0;4</coordonnees>
            <coordonnees>0;4,6;4</coordonnees>
            <coordonnees>6;4,6;0</coordonnees>
            <coordonnees>6;0,4;0</coordonnees>             
        </murs>
        <obstacles>
            <obstacle>
                <nom>but</nom>
                <coordonnees>0;2,1;2</coordonnees>  
                <coordonnees>1;2,1;3</coordonnees>
                <coordonnees>1;3,5;3</coordonnees>
                <coordonnees>5;3,5;2</coordonnees>
                <coordonnees>5;2,6;2</coordonnees>  
                <coordonnees>6;2,6;4</coordonnees>
                <coordonnees>6;4,0;4</coordonnees>
                <coordonnees>0;4,0;2</coordonnees>
            </obstacle>      
        </obstacles>
        <sortie>
            <coordEtNomPieceConnexe>3;0,piece5</coordEtNomPieceConnexe>
        </sortie>
    </piece>
    
    <piece>
        <nom>piece8</nom>
        <murs>
            <coordonnees>0;1,0;0</coordonnees>  
            <coordonnees>0;0,7;0</coordonnees>
            <coordonnees>7;0,7;4</coordonnees>
            <coordonnees>7;4,0;4</coordonnees>
            <coordonnees>0;4,0;3</coordonnees>             
        </murs>
        <sortie>
            <coordEtNomPieceConnexe>0;2,piece5</coordEtNomPieceConnexe>
        </sortie>
    </piece>
    
    <piece>
        <nom>piece9</nom>
        <murs>
            <coordonnees>0;2,0;0</coordonnees>  
            <coordonnees>0;0,2;0</coordonnees>
            <coordonnees>4;0,7;0</coordonnees>
            <coordonnees>7;0,7;6</coordonnees>
            <coordonnees>7;6,0;6</coordonnees>   
            <coordonnees>0;6,0;4</coordonnees>            
        </murs>
        <sortie>
            <coordEtNomPieceConnexe>0;3,piece5</coordEtNomPieceConnexe>
            <coordEtNomPieceConnexe>3;0,piece5</coordEtNomPieceConnexe>
        </sortie>
    </piece>
        
  </batiment>
</racine>

=== Aspard/PAndroide/data/plans/maison.xml
<?xml version="1.0" encoding="UTF-8"?>

<racine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./bp.xsd" >
<batiment>

<nom>Test</nom><piece><nom>Chambre 1</nom>
<murs>
<coordonnees>0;0,6;0</coordonnees>
<coordonnees>6;0,6;5</coordonnees>
<coordonnees>6;5,4;5</coordonnees>
<coordonnees>2;5,0;5</coordonnees>
<coordonnees>0;5,0;0</coordonnees>
</murs>
<sortie>
<coordetnompiececonnexe>3;5,Salon</coordetnompiececonnexe>
</sortie>
</piece>
<piece><nom>Chambre 2</nom>
<murs>
<coordonnees>0;0,6;0</coordonnees>
<coordonnees>6;0,6;5</coordonnees>
<coordonnees>6;5,4;5</coordonnees>
<coordonnees>2;5,0;5</coordonnees>
<coordonnees>0;5,0;0</coordonnees>
</murs>
<sortie>
<coordetnompiececonnexe>3;5,Salon</coordetnompiececonnexe>
</sortie>
</piece>
<piece><nom>Salle de bain</nom>
<murs>
<coordonnees>0;0,6;0</coordonnees>
<coordonnees>6;0,6;5</coordonnees>
<coordonnees>6;5,4;5</coordonnees>
<coordonnees>2;5,0;5</coordonnees>
<coordonnees>0;5,0;0</coordonnees>
</murs>
<sortie>
<coordetnompiececonnexe>3;5,Salon</coordetnompiececonnexe>
</sortie>
</piece>
<piece><nom>Salon</nom>
<murs>
<coordonnees>0;0,2;0</coordonnees>
<coordonnees>4;0,8;0</coordonnees>
<coordonnees>10;0,14;0</coordonnees>
<coordonnees>16;0,18;0</coordonnees>
<coordonnees>18;0,18;5</coordonnees>
<coordonnees>18;5,16;5</coordonnees>
<coordonnees>14;5,12;5</coordonnees>
<coordonnees>12;5,12;7</coordonnees>
<coordonnees>12;9,12;11</coordonnees>
<coordonnees>12;11,5;11</coordonnees>
<coordonnees>5;11,0;6</coordonnees>
<coordonnees>0;6,0;0</coordonnees>
</murs>
<sortie>
<coordetnompiececonnexe>3;0,Chambre 1</coordetnompiececonnexe>
<coordetnompiececonnexe>9;0,Chambre 2</coordetnompiececonnexe>
<coordetnompiececonnexe>15;0,Salle de bain</coordetnompiececonnexe>
<coordetnompiececonnexe>15;5,Cuisine</coordetnompiececonnexe>
<coordetnompiececonnexe>13;8,Cuisine</coordetnompiececonnexe>
</sortie>
</piece>
<piece><nom>Cuisine</nom>
<murs>
<coordonnees>0;0,2;0</coordonnees>
<coordonnees>4;0,6;0</coordonnees>
<coordonnees>6;0,6;6</coordonnees>
<coordonnees>6;6,0;6</coordonnees>
<coordonnees>0;6,0;4</coordonnees>
<coordonnees>0;2,0;0</coordonnees>
</murs>
<obstacles>
</obstacles>
<sortie>
<coordetnompiececonnexe>3;0,Salon</coordetnompiececonnexe>
<coordetnompiececonnexe>0;3,Salon</coordetnompiececonnexe>
</sortie>
</piece>
</batiment>
</racine>

=== Aspard/PAndroide/data/plans/blueprint_vide.xml
<?xml version="1.0" encoding="UTF-8"?>

<racine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./bp.xsd" >
<batiment>

<nom>Test</nom><piece><nom>piece7</nom>
<murs>
<coordonnees>2;4,0;4</coordonnees>
<coordonnees>0;4,0;0</coordonnees>
<coordonnees>0;0,6;0</coordonnees>
<coordonnees>6;0,6;4</coordonnees>
<coordonnees>6;4,4;4</coordonnees>
</murs>
<sortie>
<coordetnompiececonnexe>3;4,piece5</coordetnompiececonnexe>
</sortie>
</piece>
<piece><nom>piece1</nom>
<murs>
<coordonnees>4;5,0;5</coordonnees>
<coordonnees>0;5,0;0</coordonnees>
<coordonnees>0;0,7;0</coordonnees>
<coordonnees>7;0,7;5</coordonnees>
<coordonnees>7;5,6;5</coordonnees>
</murs>
<obstacles>
</obstacles>
<sortie>
<coordetnompiececonnexe>5;5,piece2</coordetnompiececonnexe>
</sortie>
</piece>
<piece><nom>piece2</nom>
<murs>
<coordonnees>3;0,0;0</coordonnees>
<coordonnees>0;0,0;7</coordonnees>
<coordonnees>0;7,3;7</coordonnees>
<coordonnees>3;7,3;5</coordonnees>
<coordonnees>3;5,4;5</coordonnees>
<coordonnees>6;5,6;3</coordonnees>
<coordonnees>6;1,6;0</coordonnees>
<coordonnees>6;0,5;0</coordonnees>
</murs>
<obstacles>
</obstacles>
<sortie>
<coordetnompiececonnexe>4;0,piece1</coordetnompiececonnexe>
<coordetnompiececonnexe>5;5,piece3</coordetnompiececonnexe>
<coordetnompiececonnexe>6;2,piece4</coordetnompiececonnexe>
</sortie>
</piece>
<piece><nom>piece4</nom>
<murs>
<coordonnees>0;1,0;0</coordonnees>
<coordonnees>0;0,1;0</coordonnees>
<coordonnees>3;0,4;0</coordonnees>
<coordonnees>4;0,4;9</coordonnees>
<coordonnees>4;9,1;9</coordonnees>
<coordonnees>1;9,1;5</coordonnees>
<coordonnees>1;5,0;5</coordonnees>
<coordonnees>0;5,0;3</coordonnees>
</murs>
<obstacles>
</obstacles>
<sortie>
<coordetnompiececonnexe>0;2,piece2</coordetnompiececonnexe>
<coordetnompiececonnexe>2;0,piece5</coordetnompiececonnexe>
</sortie>
</piece>
<piece><nom>piece3</nom>
<murs>
<coordonnees>1;0,0;0</coordonnees>
<coordonnees>0;0,0;4</coordonnees>
<coordonnees>0;4,3;4</coordonnees>
<coordonnees>3;4,3;0</coordonnees>
</murs>
<sortie>
<coordetnompiececonnexe>2;0,piece2</coordetnompiececonnexe>
</sortie>
</piece>
<piece><nom>piece5</nom>
<murs>
<coordonnees>0;0,4;0</coordonnees>
<coordonnees>4;0,4;1</coordonnees>
<coordonnees>4;3,4;4</coordonnees>
<coordonnees>4;4,11;4</coordonnees>
<coordonnees>11;4,11;6</coordonnees>
<coordonnees>11;6,8;6</coordonnees>
<coordonnees>6;6,4;6</coordonnees>
<coordonnees>4;6,4;8</coordonnees>
<coordonnees>4;10,4;15</coordonnees>
<coordonnees>4;15,3;15</coordonnees>
<coordonnees>1;15,0;15</coordonnees>
<coordonnees>0;15,0;6</coordonnees>
<coordonnees>0;6,-2;6</coordonnees>
<coordonnees>-4;6,-6;6</coordonnees>
<coordonnees>-6;6,-6;4</coordonnees>
<coordonnees>-6;4,-4;4</coordonnees>
<coordonnees>-2;4,0;4</coordonnees>
<coordonnees>0;4,0;0</coordonnees>
</murs>
<sortie>
<coordetnompiececonnexe>2;15,piece4</coordetnompiececonnexe>
<coordetnompiececonnexe>-3;6,piece6</coordetnompiececonnexe>
<coordetnompiececonnexe>-3;4,piece7</coordetnompiececonnexe>
<coordetnompiececonnexe>4;2,piece8</coordetnompiececonnexe>
<coordetnompiececonnexe>4;9,piece9</coordetnompiececonnexe>
<coordetnompiececonnexe>7;6,piece9</coordetnompiececonnexe>
</sortie>
</piece>
<piece><nom>piece6</nom>
<murs>
<coordonnees>2;0,0;0</coordonnees>
<coordonnees>0;0,0;4</coordonnees>
<coordonnees>0;4,6;4</coordonnees>
<coordonnees>6;4,6;0</coordonnees>
<coordonnees>6;0,4;0</coordonnees>
</murs>
<obstacles>
</obstacles>
<sortie>
<coordetnompiececonnexe>3;0,piece5</coordetnompiececonnexe>
</sortie>
</piece>
<piece><nom>piece8</nom>
<murs>
<coordonnees>0;1,0;0</coordonnees>
<coordonnees>0;0,7;0</coordonnees>
<coordonnees>7;0,7;4</coordonnees>
<coordonnees>7;4,0;4</coordonnees>
<coordonnees>0;4,0;3</coordonnees>
</murs>
<sortie>
<coordetnompiececonnexe>0;2,piece5</coordetnompiececonnexe>
</sortie>
</piece>
<piece><nom>piece9</nom>
<murs>
<coordonnees>0;2,0;0</coordonnees>
<coordonnees>0;0,2;0</coordonnees>
<coordonnees>4;0,7;0</coordonnees>
<coordonnees>7;0,7;6</coordonnees>
<coordonnees>7;6,0;6</coordonnees>
<coordonnees>0;6,0;4</coordonnees>
</murs>
<sortie>
<coordetnompiececonnexe>0;3,piece5</coordetnompiececonnexe>
<coordetnompiececonnexe>3;0,piece5</coordetnompiececonnexe>
</sortie>
</piece>
</batiment>
</racine>

=== Aspard/PAndroide/data/plans/test.xml
<?xml version="1.0" encoding="UTF-8"?>

<racine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./bp.xsd" >
<batiment>

<nom>Test</nom><piece><nom>Bureau de Yoann</nom>
<murs>
<coordonnees>4;2,4;0</coordonnees>
<coordonnees>4;0,0;0</coordonnees>
<coordonnees>0;0,0;6</coordonnees>
<coordonnees>0;6,4;6</coordonnees>
<coordonnees>4;6,4;4</coordonnees>
</murs>
<sortie>
<coordetnompiececonnexe>4;3,Couloir</coordetnompiececonnexe>
</sortie>
</piece>
<piece><nom>Salle a brainstorm</nom>
<murs>
<coordonnees>5;4,5;0</coordonnees>
<coordonnees>5;0,0;0</coordonnees>
<coordonnees>0;0,0;7</coordonnees>
<coordonnees>0;7,5;7</coordonnees>
<coordonnees>5;7,5;6</coordonnees>
</murs>
<sortie>
<coordetnompiececonnexe>5;5,Bureau du chef</coordetnompiececonnexe>
</sortie>
</piece>
<piece><nom>Bureau du chef</nom>
<murs>
<coordonnees>0;3,0;0</coordonnees>
<coordonnees>0;0,7;0</coordonnees>
<coordonnees>7;0,7;3</coordonnees>
<coordonnees>7;3,5;3</coordonnees>
<coordonnees>5;3,5;4</coordonnees>
<coordonnees>5;6,3;6</coordonnees>
<coordonnees>1;6,0;6</coordonnees>
<coordonnees>0;6,0;5</coordonnees>
</murs>
<sortie>
<coordetnompiececonnexe>0;4,Salle a brainstorm</coordetnompiececonnexe>
<coordetnompiececonnexe>5;5,Cagibi</coordetnompiececonnexe>
<coordetnompiececonnexe>2;6,Compta</coordetnompiececonnexe>
</sortie>
</piece>
<piece><nom>Compta</nom>
<murs>
<coordonnees>1;0,0;0</coordonnees>
<coordonnees>0;0,0;1</coordonnees>
<coordonnees>0;3,0;4</coordonnees>
<coordonnees>0;4,9;4</coordonnees>
<coordonnees>9;4,9;1</coordonnees>
<coordonnees>9;1,5;1</coordonnees>
<coordonnees>5;1,5;0</coordonnees>
<coordonnees>5;0,3;0</coordonnees>
</murs>
<sortie>
<coordetnompiececonnexe>2;0,Bureau du chef</coordetnompiececonnexe>
<coordetnompiececonnexe>0;2,Couloir</coordetnompiececonnexe>
</sortie>
</piece>
<piece><nom>Cagibi</nom>
<murs>
<coordonnees>0;1,0;0</coordonnees>
<coordonnees>0;0,4;0</coordonnees>
<coordonnees>4;0,4;3</coordonnees>
<coordonnees>4;3,0;3</coordonnees>
</murs>
<sortie>
<coordetnompiececonnexe>0;2,Bureau du chef</coordetnompiececonnexe>
</sortie>
</piece>
<piece><nom>Couloir</nom>
<murs>
<coordonnees>0;0,0;4</coordonnees>
<coordonnees>0;4,1;4</coordonnees>
<coordonnees>3;4,4;4</coordonnees>
<coordonnees>4;4,4;7</coordonnees>
<coordonnees>4;9,4;11</coordonnees>
<coordonnees>4;11,6;11</coordonnees>
<coordonnees>6;11,6;8</coordonnees>
<coordonnees>6;6,6;4</coordonnees>
<coordonnees>8;4,10;4</coordonnees>
<coordonnees>12;4,15;4</coordonnees>
<coordonnees>15;4,15;3</coordonnees>
<coordonnees>15;1,15;0</coordonnees>
<coordonnees>15;0,6;0</coordonnees>
<coordonnees>6;0,6;-2</coordonnees>
<coordonnees>6;-4,6;-6</coordonnees>
<coordonnees>4;-6,4;-4</coordonnees>
<coordonnees>4;-2,4;0</coordonnees>
<coordonnees>4;0,0;0</coordonnees>
</murs>
<sortie>
<coordetnompiececonnexe>15;2,Compta</coordetnompiececonnexe>
<coordetnompiececonnexe>6;-3,Bureau de Helene</coordetnompiececonnexe>
<coordetnompiececonnexe>4;-3,Bureau de Yoann</coordetnompiececonnexe>
<coordetnompiececonnexe>2;4,Bureau de Yacine</coordetnompiececonnexe>
<coordetnompiececonnexe>4;8,Bureau de Yacine</coordetnompiececonnexe>
<coordetnompiececonnexe>6;7,Salle de detente</coordetnompiececonnexe>
<coordetnompiececonnexe>7;4,Salle de detente</coordetnompiececonnexe>
<coordetnompiececonnexe>11;4,Salle de detente</coordetnompiececonnexe>
<coordetnompiececonnexe>5;-6,Anneau pour jogging</coordetnompiececonnexe>
</sortie>
</piece>
<piece><nom>Bureau de Helene</nom>
<murs>
<coordonnees>0;2,0;0</coordonnees>
<coordonnees>0;0,4;0</coordonnees>
<coordonnees>4;0,4;6</coordonnees>
<coordonnees>4;6,0;6</coordonnees>
<coordonnees>0;6,0;4</coordonnees>
</murs>
<sortie>
<coordetnompiececonnexe>0;3,Couloir</coordetnompiececonnexe>
</sortie>
</piece>
<piece><nom>Bureau de Yacine</nom>
<murs>
<coordonnees>1;0,0;0</coordonnees>
<coordonnees>0;0,0;7</coordonnees>
<coordonnees>0;7,4;7</coordonnees>
<coordonnees>4;7,4;5</coordonnees>
<coordonnees>4;3,4;0</coordonnees>
<coordonnees>4;0,3;0</coordonnees>
</murs>
<sortie>
<coordetnompiececonnexe>2;0,Couloir</coordetnompiececonnexe>
<coordetnompiececonnexe>4;4,Couloir</coordetnompiececonnexe>
</sortie>
</piece>
<piece><nom>Salle de detente</nom>
<murs>
<coordonnees>2;0,4;0</coordonnees>
<coordonnees>6;0,6;2</coordonnees>
<coordonnees>6;4,6;7</coordonnees>
<coordonnees>6;7,0;7</coordonnees>
<coordonnees>0;7,0;4</coordonnees>
<coordonnees>0;2,0;0</coordonnees>
</murs>
<sortie>
<coordetnompiececonnexe>0;3,Couloir</coordetnompiececonnexe>
<coordetnompiececonnexe>1;0,Couloir</coordetnompiececonnexe>
<coordetnompiececonnexe>5;0,Couloir</coordetnompiececonnexe>
<coordetnompiececonnexe>6;3,jardin</coordetnompiececonnexe>
</sortie>
</piece>
<piece><nom>Anneau pour jogging</nom>
<murs>
<coordonnees>0;0,10;0</coordonnees>
<coordonnees>10;0,10;-1</coordonnees>
<coordonnees>10;-1,19;-1</coordonnees>
<coordonnees>19;-1,19;0</coordonnees>
<coordonnees>19;0,34;0</coordonnees>
<coordonnees>34;0,34;21</coordonnees>
<coordonnees>34;21,0;21</coordonnees>
<coordonnees>0;21,0;0</coordonnees>
</murs>
<obstacles>
<obstacle>
<coordonnees>2.0;2.0,12.0;2.0</coordonnees>
<coordonnees>12.0;2.0,12.0;2.0</coordonnees>
<coordonnees>12.0;2.0,12.0;2.0</coordonnees>
<coordonnees>12.0;2.0,12.0;2.0</coordonnees>
<coordonnees>12.0;2.0,12.0;2.0</coordonnees>
<coordonnees>12.0;2.0,12.0;2.0</coordonnees>
<coordonnees>12.0;2.0,12.0;2.0</coordonnees>
<coordonnees>12.0;2.0,12.0;2.0</coordonnees>
<coordonnees>12.0;2.0,12.0;1.0</coordonnees>
<coordonnees>12.0;1.0,12.0;1.0</coordonnees>
<coordonnees>12.0;1.0,12.0;1.0</coordonnees>
<coordonnees>12.0;1.0,12.0;1.0</coordonnees>
<coordonnees>12.0;1.0,12.0;1.0</coordonnees>
<coordonnees>12.0;1.0,12.0;1.0</coordonnees>
<coordonnees>12.0;1.0,12.0;1.0</coordonnees>
<coordonnees>12.0;1.0,12.0;1.0</coordonnees>
<coordonnees>12.0;1.0,17.0;1.0</coordonnees>
<coordonnees>17.0;1.0,17.0;1.0</coordonnees>
<coordonnees>17.0;1.0,17.0;1.0</coordonnees>
<coordonnees>17.0;1.0,17.0;1.0</coordonnees>
<coordonnees>17.0;1.0,17.0;1.0</coordonnees>
<coordonnees>17.0;1.0,17.0;1.0</coordonnees>
<coordonnees>17.0;1.0,17.0;1.0</coordonnees>
<coordonnees>17.0;1.0,17.0;1.0</coordonnees>
<coordonnees>17.0;1.0,17.0;2.0</coordonnees>
<coordonnees>17.0;2.0,17.0;2.0</coordonnees>
<coordonnees>17.0;2.0,17.0;2.0</coordonnees>
<coordonnees>17.0;2.0,17.0;2.0</coordonnees>
<coordonnees>17.0;2.0,17.0;2.0</coordonnees>
<coordonnees>17.0;2.0,17.0;2.0</coordonnees>
<coordonnees>17.0;2.0,17.0;2.0</coordonnees>
<coordonnees>17.0;2.0,17.0;2.0</coordonnees>
<coordonnees>17.0;2.0,32.0;2.0</coordonnees>
<coordonnees>32.0;2.0,32.0;2.0</coordonnees>
<coordonnees>32.0;2.0,32.0;2.0</coordonnees>
<coordonnees>32.0;2.0,32.0;2.0</coordonnees>
<coordonnees>32.0;2.0,32.0;2.0</coordonnees>
<coordonnees>32.0;2.0,32.0;2.0</coordonnees>
<coordonnees>32.0;2.0,32.0;2.0</coordonnees>
<coordonnees>32.0;2.0,32.0;2.0</coordonnees>
<coordonnees>32.0;2.0,32.0;19.0</coordonnees>
<coordonnees>32.0;19.0,32.0;19.0</coordonnees>
<coordonnees>32.0;19.0,32.0;19.0</coordonnees>
<coordonnees>32.0;19.0,32.0;19.0</coordonnees>
<coordonnees>32.0;19.0,32.0;19.0</coordonnees>
<coordonnees>32.0;19.0,32.0;19.0</coordonnees>
<coordonnees>32.0;19.0,32.0;19.0</coordonnees>
<coordonnees>32.0;19.0,32.0;19.0</coordonnees>
<coordonnees>32.0;19.0,2.0;19.0</coordonnees>
<coordonnees>2.0;19.0,2.0;19.0</coordonnees>
<coordonnees>2.0;19.0,2.0;19.0</coordonnees>
<coordonnees>2.0;19.0,2.0;19.0</coordonnees>
<coordonnees>2.0;19.0,2.0;19.0</coordonnees>
<coordonnees>2.0;19.0,2.0;19.0</coordonnees>
<coordonnees>2.0;19.0,2.0;19.0</coordonnees>
<coordonnees>2.0;19.0,2.0;19.0</coordonnees>
<coordonnees>2.0;19.0,2.0;2.0</coordonnees>
</obstacle>
<obstacle>
</obstacle>
</obstacles>
<sortie>
<coordetnompiececonnexe>7;2,Couloir</coordetnompiececonnexe>
</sortie>
</piece>
<piece><nom>jardin</nom>
<murs>
<coordonnees>0;0,12;0</coordonnees>
<coordonnees>12;0,12;-3</coordonnees>
<coordonnees>12;-3,8;-3</coordonnees>
<coordonnees>8;-3,8;-4</coordonnees>
<coordonnees>8;-4,12;-4</coordonnees>
<coordonnees>12;-4,12;-7</coordonnees>
<coordonnees>12;-7,10;-7</coordonnees>
<coordonnees>10;-7,10;-10</coordonnees>
<coordonnees>10;-10,18;-10</coordonnees>
<coordonnees>18;-10,18;7</coordonnees>
<coordonnees>18;7,0;7</coordonnees>
<coordonnees>0;7,0;4</coordonnees>
<coordonnees>0;2,0;0</coordonnees>
</murs>
<sortie>
<coordetnompiececonnexe>0;3,Salle de detente</coordetnompiececonnexe>
</sortie>
</piece>
</batiment>
</racine>
